schema_version: 1

context:
  name: dashscope
  version: "1.25.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/dashscope/dashscope-sdk-python/archive/v${{ version }}.tar.gz
  sha256: 0f68c6532e44b418d4154bdb01b922afccd33bf21218f70e560247d5af02e390

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dashscope = dashscope.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - aiohttp
    - requests
    - websocket-client
    - cryptography
    - certifi

tests:
  - python:
      imports:
        - dashscope
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
    script:
      - dashscope --help

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://dashscope.aliyun.com/
  repository: https://github.com/dashscope/dashscope-sdk-python
  summary: Python SDK for dashscope [model studio](https://www.alibabacloud.com/en/product/modelstudio?_p_lc=1)

extra:
  recipe-maintainers:
    - shermansiu
